# yaml-language-server: $schema=../patch_yaml_model.json
# from this bit of code
# if record_name == "conda-content-trust" and record.get("timestamp", 0) < 1685589411000:  # 2023-06-01
#     _replace_pin("cryptography", "cryptography <41.0.0a0", record["depends"], record)
if:
  name: conda-content-trust
  timestamp_lt: 1685589411000
then:
  - replace_depends:
      old: cryptography
      new: cryptography <41.0.0a0
